apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-stats-stage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-stats
        env: stage
    spec:
      containers:
      - name: rabbitmq-stats
        image: undeadops/rabbitmq-stats:2.0
        env:
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: rabbitmq-stats-secrets
                key: rabbitmq_url
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-stats-secrets
                key: rabbitmq_username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-stats-secrets
                key: rabbitmq_password
          - name: RABBITMQ_EXCLUDE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-stats-secrets
                key: rabbitmq_exclude
          - name: INTERVAL
            valueFrom:
              secretKeyRef:
                name: rabbitmq-stats-secrets
                key: interval
          - name: STATSD_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq-stats-secrets
                key: statsd_host
          - name: STATSD_PORT
            valueFrom:
              secretKeyRef:
                name: rabbitmq-stats-secrets
                key: statsd_port
                
